version: "3"
services:
  web:
    build: .
    ports:
      - "8085:80"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/flask-blogger
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    env_file:
      - .env
